objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Control_Product__c</fullName>
        <label>Control Product</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

objects/Product_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Product_Code__c</fullName>
        <formula>Product__r.ProductCode</formula>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <label>Product Line Item</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Product Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product line items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/GetRelatedProducts.cls
public class GetRelatedProducts {

    @InvocableMethod(label='Get Related Products' description='Get Related products matching to Master Service PI')
    public static List<RelatedProducts> createRelated(List <GetMasterPI> pis){
        
        Product_Line_Item__c masterPIs = pis.get(0).masterPI;
        String masterProduct = masterPIs.Product_Code__c;
        String controlProductName;
        List <String> relatedProdNames = new List <String> ();
        List<RelatedProducts> relatedProductList = new List<RelatedProducts>();
        List<Product2> relatedProd = [select Id, Name, Family, Control_Product__c from Product2 WHERE Family = 'Related'];
        
        
        //start of logic
        for(Product2 productObj : relatedProd) {
            if(productObj.Control_Product__c != NULL)  {
                controlProductName = productObj.Control_Product__c;
                
                if(controlProductName.contains(masterProduct) ) {
                    relatedProdNames.add(productObj.Name);
                }
            }
        }

        //end of logic
        
        //parse outputs
        RelatedProducts dp = new RelatedProducts();
        dp.relatedPName = relatedProdNames;
        relatedProductList.add(dp);        
        return relatedProductList; 
    }
    
    public class GetMasterPI{        
        @InvocableVariable
        public Product_Line_Item__c masterPI;
    }
    
    public class RelatedProducts{        
        @InvocableVariable
        public List<string> relatedPName;
    }
    
}